// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3494a5bc-21f5-4ad0-a89e-67bcb007dbe3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zL1Kz93uv",
    "aws_user_pools_web_client_id": "4hkvergqs0qsk73mdsdtvuln76",
    "aws_appsync_graphqlEndpoint": "https://rlempudrmrhnvg5gxe4jpvbxti.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "nessserverless6dbcd64ff0484ea482221079014027fa",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "nessserverless-20181121140317--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1ppdfb27zn21v.cloudfront.net"
};


export default awsmobile;
