// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fb2e640a-53c2-4c78-8166-f764498ab743",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GpEVaKqEU",
    "aws_user_pools_web_client_id": "6n17h6g9afm1euek7hq70865dg",
    "aws_appsync_graphqlEndpoint": "https://osmn6giuh5doxjiuw7ctrq5ohu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "ness-web-bucket",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;