// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ba0acd06-516c-4f31-a4e0-8ea876b9d4ec",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3nxF02K0r",
    "aws_user_pools_web_client_id": "7m0rrfolkdu7jfijuqvhso3cah"
};


export default awsmobile;
