// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
<<<<<<< HEAD
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6d892b00-076b-4053-a42d-33a8432b9872",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_eSPnqZTJn",
    "aws_user_pools_web_client_id": "5bmm982pkv9m64qr5sogdb2p0v",
    "aws_appsync_graphqlEndpoint": "https://qc5s7omeenexxehg42bugzldya.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "ness-web-app",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_mobile_analytics_app_id": "8a66b676d8f84d7089ec7d058b8bf237",
    "aws_mobile_analytics_app_region": "us-east-1"
=======
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fb2e640a-53c2-4c78-8166-f764498ab743",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GpEVaKqEU",
    "aws_user_pools_web_client_id": "6n17h6g9afm1euek7hq70865dg",
    "aws_appsync_graphqlEndpoint": "https://osmn6giuh5doxjiuw7ctrq5ohu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "ness-web-bucket",
    "aws_user_files_s3_bucket_region": "us-east-1"
>>>>>>> b55177048203d07d86624cf53c6ec81f34827355
};


export default awsmobile;